import Footer from "@/components/Footer/Footer";
import NavBar from "@/components/NavBar/NavBar";
import "./globals.css"


export const metadata = {
  title: "Social-Media",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className="container">
        <NavBar></NavBar>
        {children}
        <Footer></Footer>
        </div>

        </body>
    </html>
  );
}
